
const $=s=>document.querySelector(s),TABS=['Overview','Dataset Overview','Dataset Comparison','Dataset Reports','Warehouse & OLAP','Preprocessing','Association Rules','Classification','Regression','Clustering','Insights','Data Explorer','What-if Predict'];
const CONT=['Age','DistanceFromHome','MonthlyIncome','PercentSalaryHike','TotalWorkingYears','YearsAtCompany','YearsInCurrentRole'];
const COLS=['Age','BusinessTravel','Department','DistanceFromHome','EducationField','EnvironmentSatisfaction','JobLevel','JobRole','JobSatisfaction','MaritalStatus','MonthlyIncome','OverTime','PercentSalaryHike','TotalWorkingYears','WorkLifeBalance','YearsAtCompany','YearsInCurrentRole'];
const NUM=[...CONT,'EnvironmentSatisfaction','JobLevel','JobSatisfaction','WorkLifeBalance'];
let ALL=[],F=[],Dm=[],charts={},R={};
const rng=s=>()=>(s=(s*1664525+1013904223)>>>0)/4294967296,sum=(a,f=x=>x)=>a.reduce((s,x)=>s+f(x),0),isY=r=>r[TGT]==POS;
function parse(t){return csvParse(t)}
function demo(){const r=rng(7),pk=a=>a[Math.floor(r()*a.length)],I=n=>1+Math.floor(r()*n),out=[],RL={'Research & Development':['Research Scientist','Laboratory Technician','Manufacturing Director','Research Director'],Sales:['Sales Executive','Sales Representative','Manager'],'Human Resources':['Human Resources','Manager']};
for(let i=0;i<2500;i++){const age=18+Math.floor(r()*43),tw=Math.min(35,Math.floor((age-18)*(.1+.85*r()))),lvl=Math.min(5,Math.max(1,1+Math.floor(tw/6+(r()-.5)*2.2))),inc=Math.round(Math.min(21000,Math.max(2000,[0,3200,6200,9000,14000,18000][lvl]+(r()-.5)*3500+tw*40))),dp=pk(['Research & Development','Research & Development','Sales','Human Resources']),ot=r()<.3?'Yes':'No',ms=pk(['Single','Married','Married','Divorced']),wl=I(4),bt=pk(['Travel_Rarely','Travel_Rarely','Travel_Frequently','Non-Travel']),ya=Math.min(tw,Math.floor(r()*r()*20)),z=-1.6+1.3*(ot=='Yes')+.8*(ms=='Single')+.9*(lvl==1)+.5*(wl==1)+.3*(bt=='Travel_Frequently')-.03*(age-35)-.00008*(inc-6000);
out.push({EmployeeID:'E'+(1001+i),Age:age,Attrition:r()<1/(1+Math.exp(-z))?'Yes':'No',BusinessTravel:bt,Department:dp,DistanceFromHome:I(29),EducationField:pk(['Life Sciences','Medical','Marketing','Technical Degree','Human Resources','Other']),EnvironmentSatisfaction:I(4),JobLevel:lvl,JobRole:pk(RL[dp]),JobSatisfaction:I(4),MaritalStatus:ms,MonthlyIncome:inc,OverTime:ot,PercentSalaryHike:10+I(15),TotalWorkingYears:tw,WorkLifeBalance:wl,YearsAtCompany:ya,YearsInCurrentRole:Math.floor(r()*(ya+1))})}return out}
function disc(rows){const mm={};CONT.forEach(c=>{const v=rows.map(r=>r[c]);mm[c]=[Math.min(...v),Math.max(...v)]});
return rows.map(r=>{const o={[TGT]:r[TGT]};COLS.forEach(c=>{if(CONT.includes(c)){const[a,b]=mm[c],w=(b-a)/3||1;o[c]=['Low','Mid','High'][Math.min(2,Math.floor((r[c]-a)/w))]}else o[c]=String(r[c])});return o})}
const H=(y,n)=>y&&y<n?-(y/n*Math.log2(y/n)+(n-y)/n*Math.log2((n-y)/n)):0;
function gain(rows,c,b){const g={};rows.forEach(r=>{(g[r[c]]=g[r[c]]||[0,0])[isY(r)?0:1]++});let s=0;for(const k in g){const[a,d]=g[k];s+=(a+d)/rows.length*H(a,a+d)}return b-s}
function tree(rows,cols,d){const n=rows.length,y=rows.filter(isY).length,lab=y*2>=n?'Yes':'No';if(d==0||n<30||!y||y==n)return{lab,n,y};const b=H(y,n);let best=null,bg=.002;cols.forEach(c=>{const g=gain(rows,c,b);if(g>bg){bg=g;best=c}});if(!best)return{lab,n,y};const k={};rows.forEach(r=>(k[r[best]]=k[r[best]]||[]).push(r));const ch={};for(const v in k)ch[v]=tree(k[v],cols.filter(c=>c!=best),d-1);return{lab,n,y,attr:best,ch}}
const pt=(t,r)=>{while(t.attr&&t.ch[r[t.attr]])t=t.ch[r[t.attr]];return t.lab};
const tr=t=>t.attr?`<ul>${Object.entries(t.ch).map(([k,v])=>`<li>${t.attr} = <b>${k}</b>${v.attr?'':` → <span class="${v.lab=='Yes'?'y':'n'}">${v.lab}</span> <small class="mu">(${v.n} emp, ${v.y} left)</small>`}${tr(v)}</li>`).join('')}</ul>`:'';
function nb(tr){const m={Yes:{n:0,c:{}},No:{n:0,c:{}}};tr.forEach(r=>{const z=m[isY(r)?'Yes':'No'];z.n++;COLS.forEach(c=>{const k=c+'='+r[c];z.c[k]=(z.c[k]||0)+1})});return r=>{let b,bs=-1e9;for(const k in m){let s=Math.log((m[k].n+1)/tr.length);COLS.forEach(c=>s+=Math.log(((m[k].c[c+'='+r[c]]||0)+1)/(m[k].n+4)));if(s>bs){bs=s;b=k}}return b}}
function ev(te,f){let tp=0,fp=0,fn=0,tn=0;te.forEach(r=>{const p=f(r);if(isY(r))p=='Yes'?tp++:fn++;else p=='Yes'?fp++:tn++});const pr=tp/(tp+fp||1),rc=tp/(tp+fn||1);return{acc:(tp+tn)/te.length,pr,rc,f1:2*pr*rc/(pr+rc||1),tp,fp,fn,tn}}
function ols(X,y){const n=X.length,p=X[0].length+1,A=Array.from({length:p},()=>Array(p+1).fill(0));X.forEach((x,i)=>{const v=[1,...x];for(let a=0;a<p;a++){for(let b=0;b<p;b++)A[a][b]+=v[a]*v[b];A[a][p]+=v[a]*y[i]}});
for(let i=0;i<p;i++){let m=i;for(let r=i+1;r<p;r++)if(Math.abs(A[r][i])>Math.abs(A[m][i]))m=r;[A[i],A[m]]=[A[m],A[i]];for(let r=0;r<p;r++)if(r!=i){const f=A[r][i]/A[i][i];for(let c=i;c<=p;c++)A[r][c]-=f*A[i][c]}}
const b=A.map((r,i)=>r[p]/r[i]),pr=X.map(x=>b[0]+x.reduce((s,v,i)=>s+v*b[i+1],0)),my=sum(y)/n;return{b,pr,r2:1-sum(y,(v,i)=>0)+0}}
function reg(X,y){const o=ols(X,y),n=y.length,my=sum(y)/n,sst=sum(y,v=>(v-my)**2),sse=sum(y.map((v,i)=>(v-o.pr[i])**2));o.r2=1-sse/sst;o.mae=sum(y.map((v,i)=>Math.abs(v-o.pr[i])))/n;return o}
function km(rows,K=KK()){const Fs=KF,st=Fs.map(f=>{const v=rows.map(r=>r[f]),m=sum(v)/v.length;return[m,Math.sqrt(sum(v,x=>(x-m)**2)/v.length)||1]}),P=rows.map(r=>Fs.map((f,i)=>(r[f]-st[i][0])/st[i][1])),r=rng(3);let C=KI(K).map(()=>P[Math.floor(r()*P.length)].slice()),a=[];
for(let t=0;t<50;t++){a=P.map(p=>{let b=0,bd=1e9;C.forEach((c,j)=>{const d=sum(c,(v,i)=>0)+c.reduce((s,v,i)=>s+(v-p[i])**2,0);if(d<bd){bd=d;b=j}});return b});C=C.map((c,j)=>{const m=P.filter((_,i)=>a[i]==j);return m.length?c.map((_,d)=>sum(m,p=>p[d])/m.length):c})}
km.W=P.reduce((s,p,i)=>s+C[a[i]].reduce((t,v,d)=>t+(v-p[d])**2,0),0);const inc=KI(K).map(j=>{const m=rows.filter((_,i)=>a[i]==j);return m.length?sum(m,x=>x[KF[0]])/m.length:0}),o=KI(K).sort((x,y)=>inc[x]-inc[y]),rk={};o.forEach((v,i)=>rk[v]=i);return a.map(x=>rk[x])}
function mk(id,cfg){if(window.colorize)colorize(cfg);charts[id]&&charts[id].destroy();cfg.options=Object.assign({responsive:true,maintainAspectRatio:false},cfg.options||{});charts[id]=new Chart($('#'+id),cfg)}
function rate(id,c,t){const g={};F.forEach((r,i)=>{const k=CONT.includes(c)?Dm[i][c]:r[c];(g[k]=g[k]||[0,0])[isY(r)?0:1]++});const O=['Low','Mid','High'],ks=Object.keys(g).sort((a,b)=>O.includes(a)?O.indexOf(a)-O.indexOf(b):isNaN(a)?a.localeCompare(b):a-b);mk(id,{type:'bar',data:{labels:ks,datasets:[{data:ks.map(k=>+(100*g[k][0]/(g[k][0]+g[k][1])).toFixed(1)),backgroundColor:'#e5484d'}]},options:{plugins:{title:{display:true,text:t},legend:{display:false}},scales:{y:{beginAtZero:true,title:{display:true,text:'Attrition %'}}}}})}
const mean=(a,f)=>a.length?sum(a,f)/a.length:0,fx=(v,d=1)=>(+v).toLocaleString(undefined,{maximumFractionDigits:d});
function shell(){$('#app').innerHTML=`
<section class="pn" id="p0"><div class="g k" id="kp"></div><div class="g"><div class="c"><div class="ch"><canvas id="c0"></canvas></div></div><div class="c"><div class="ch"><canvas id="c1"></canvas></div></div><div class="c"><div class="ch"><canvas id="c2"></canvas></div></div><div class="c"><div class="ch"><canvas id="c3"></canvas></div></div><div class="c"><div class="ch"><canvas id="c4"></canvas></div></div><div class="c"><div class="ch"><canvas id="c5"></canvas></div></div><div class="c w"><h3>Staged data preview (first 8 rows)</h3><div id="pv"></div></div></div></section>
<section class="pn" id="p1"><div class="g"><div class="c w"><h3>Star schema (Dimensional model)</h3><div id="star"></div><p class="mu">Tier 1: ETL from CSV/OLTP → Tier 2: OLAP cube (this pivot) → Tier 3: mining &amp; dashboards.</p></div>
<div class="c w"><h3>OLAP cube — pivot, drill-down &amp; roll-up</h3><div class="sc">Rows <select id="pr"></select> Columns <select id="pc"></select> Measure <select id="pm"><option value="r">${TGT} rate</option><option value="n">Headcount</option><option value="inc">Avg ${MEAS}</option></select><span class="mu">Slice with the department selector above. “All” row/column = roll-up.</span></div><div id="pvt"></div></div></div></section>
<section class="pn" id="p2"><div class="g"><div class="c"><h3>Information Gain ranking (target = ${TGT})</h3><div class="ch" style="height:420px"><canvas id="c6"></canvas></div></div><div class="c"><h3>Numeric summary</h3><div id="ns"></div></div></div></section>
<section class="pn" id="p3"><div class="c"><h3>Apriori — rules ⇒ ${TGT}=${POS}</h3><div class="sc">Min support <input type="range" id="sup" min="1" max="30" value="8"> <b id="sv"></b> Min confidence <input type="range" id="conf" min="40" max="95" value="60"> <b id="cv"></b></div><div id="ar"></div></div></section>
<section class="pn" id="p4"><div class="g"><div class="c w"><div class="sc">Tree depth <input type="range" id="td" min="1" max="6" value="3"><b id="tdv">3</b> Training split <input type="range" id="sp" min="50" max="90" step="5" value="70"><b id="spv">70</b>% <span class="mu">release the slider to retrain</span></div></div><div class="c"><h3>Model comparison (70/30 hold-out)</h3><div id="cm"></div></div><div class="c"><h3>Confusion matrices</h3><div id="cf"></div></div><div class="c w"><h3>Decision tree (J48-style, information gain, depth set by slider)</h3><div id="tt"></div></div></div></section>
<section class="pn" id="p5"><div class="g"><div class="c"><h3>Model 1 — ${M1T} ~ ${M1X.join(' + ')}</h3><div id="r1"></div></div><div class="c"><h3>Model 2 — ${M2T} ~ ${M2X.join(' + ')}</h3><div id="r2"></div></div><div class="c w"><div class="ch" style="height:320px"><canvas id="c7"></canvas></div></div></div></section>
<section class="pn" id="p6"><div class="g"><div class="c"><h3>K-Means workforce segments</h3><div class="sc">Clusters K <input type="range" id="kk" min="2" max="6" value="3"><b id="kv">3</b></div><div id="kt"></div></div><div class="c"><div class="ch" style="height:340px"><canvas id="c8"></canvas></div></div></div></section>
<section class="pn" id="p7"><div class="c"><h3>Auto-generated findings &amp; HR recommendations</h3><div id="in"></div></div></section>`;
const o=DIMS().map(x=>`<option>${x}</option>`).join('');$('#pr').innerHTML=o;$('#pc').innerHTML=o;$('#pc').selectedIndex=Math.min(1,DIMS().length-1);['pr','pc','pm'].forEach(i=>$('#'+i).onchange=pivot);$('#sup').oninput=$('#conf').oninput=apr;if(window.extraShell)extraShell();go(0)}
function go(i){document.querySelectorAll('.pn').forEach((p,j)=>p.classList.toggle('on',i==j));document.querySelectorAll('nav button').forEach((b,j)=>b.classList.toggle('on',i==j))}
function pivot(){const A=$('#pr').value,B=$('#pc').value,M=$('#pm').value,rs=[...new Set(F.map(r=>r[A]))].sort(),cs=[...new Set(F.map(r=>r[B]))].sort(),cell=(a,b)=>{const g=F.filter(r=>(a==null||r[A]==a)&&(b==null||r[B]==b));return !g.length?'–':M=='n'?g.length:M=='inc'?fx(mean(g,r=>r[MEAS]),0):fx(100*g.filter(isY).length/g.length)+'%'};
$('#pvt').innerHTML=`<table><tr><th>${A} × ${B}</th>${cs.map(c=>`<th>${c}</th>`).join('')}<th>All</th></tr>${rs.map(r=>`<tr><th>${r}</th>${cs.map(c=>`<td>${cell(r,c)}</td>`).join('')}<td><b>${cell(r,null)}</b></td></tr>`).join('')}<tr><th>All</th>${cs.map(c=>`<td><b>${cell(null,c)}</b></td>`).join('')}<td><b>${cell(null,null)}</b></td></tr></table>`}
function apr(){const ms=+$('#sup').value/100,mc=+$('#conf').value/100;$('#sv').textContent=(ms*100)+'%';$('#cv').textContent=(mc*100)+'%';const n=Dm.length,py=Dm.filter(isY).length/n,it={};Dm.forEach((r,i)=>COLS.forEach(c=>(it[c+'='+r[c]]=it[c+'='+r[c]]||[]).push(i)));
const ks=Object.keys(it).filter(k=>it[k].length/n>=ms),mask={};ks.forEach(k=>{const m=new Uint8Array(n);it[k].forEach(i=>m[i]=1);mask[k]=m});const Y=Dm.map(r=>isY(r)?1:0),res=[],add=(name,idx)=>{let y=0;idx.forEach(i=>y+=Y[i]);const s=y/n,c=y/idx.length;if(s>=ms&&c>=mc)res.push({name,s,c,l:c/py})};
ks.forEach(k=>add(k,it[k]));for(let a=0;a<ks.length;a++)for(let b=a+1;b<ks.length;b++){if(ks[a].split('=')[0]==ks[b].split('=')[0])continue;add(ks[a]+' ∧ '+ks[b],it[ks[a]].filter(i=>mask[ks[b]][i]))}
res.sort((a,b)=>b.l-a.l);R.rules=res;$('#ar').innerHTML=`<p class="mu">${res.length} rules found; top 12 by lift. Discretized bins: Low / Mid / High.</p><table><tr><th>Rule</th><th>Support</th><th>Confidence</th><th>Lift</th></tr>${res.slice(0,12).map(r=>`<tr><td>${r.name} ⇒ <span class="y">${TGT}=${POS}</span></td><td>${r.s.toFixed(3)}</td><td>${r.c.toFixed(3)}</td><td>${r.l.toFixed(2)}</td></tr>`).join('')||'<tr><td>No rules — lower the thresholds</td></tr>'}</table>`}
function render(){F=flt(ALL);if(F.length<50){$('#fc').textContent='Only '+F.length+' employees match - widen the filters (need at least 50)';return}Dm=disc(F);const n=F.length,ya=F.filter(isY).length;
$('#kp').innerHTML=[['Records',n.toLocaleString()],[TGT+' rate',fx(100*ya/n)+'%'],[POS+' / other',ya+' / '+(n-ya)],...KF.map(c=>['Avg '+c,fx(mean(F,r=>r[c]),1)])].map(([l,v])=>`<div class="c"><div class="kl">${l}</div><div class="kv">${v}</div></div>`).join('');
mk('c0',{type:'doughnut',data:{labels:['Left','Stayed'],datasets:[{data:[ya,n-ya],backgroundColor:['#e5484d','#2f5bea']}]},options:{plugins:{title:{display:true,text:'Attrition split'}}}});
TOPA(5).forEach((c,i)=>rate('c'+(i+1),c,TGT+' % by '+c));
$('#pv').innerHTML=`<table><tr>${Object.keys(F[0]).map(k=>`<th>${k}</th>`).join('')}</tr>${F.slice(0,8).map(r=>`<tr>${Object.values(r).map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</table>`;
pivot();const b=H(ya,n),ig=COLS.map(c=>[c,gain(Dm,c,b)]).sort((a,b)=>b[1]-a[1]);R.ig=ig;
mk('c6',{type:'bar',data:{labels:ig.map(x=>x[0]),datasets:[{data:ig.map(x=>+x[1].toFixed(4)),backgroundColor:'#2f5bea'}]},options:{indexAxis:'y',plugins:{legend:{display:false}}}});

$('#ns').innerHTML=`<table><tr><th>Attribute</th><th>Min</th><th>Mean</th><th>Max</th></tr>${CONT.map(c=>`<tr><td>${c}</td><td>${Math.min(...F.map(r=>r[c]))}</td><td>${fx(mean(F,r=>r[c]))}</td><td>${Math.max(...F.map(r=>r[c]))}</td></tr>`).join('')}</table>`;apr();
const r=rng(42),ix=Dm.map((_,i)=>i).sort(()=>r()-.5),cut=Math.floor(n*TS()/100),trn=ix.slice(0,cut).map(i=>Dm[i]),te=ix.slice(cut).map(i=>Dm[i]),T=tree(trn,COLS,TD()),M1=ev(te,pt.bind(null,T)),M2=ev(te,nb(trn));R.m=[M1,M2];R.sp={trn,te,T};
$('#cm').innerHTML=`<table><tr><th>Metric</th><th>J48-style Tree</th><th>Naive Bayes</th></tr>${[['Accuracy','acc'],['Precision (Yes)','pr'],['Recall (Yes)','rc'],['F1 (Yes)','f1']].map(([l,k])=>`<tr><td>${l}</td><td><b>${(M1[k]*100).toFixed(1)}%</b></td><td><b>${(M2[k]*100).toFixed(1)}%</b></td></tr>`).join('')}</table><p class="mu">Train ${trn.length} / Test ${te.length} records.</p>`;
$('#cf').innerHTML=[['Decision Tree',M1],['Naive Bayes',M2]].map(([t,m])=>`<b>${t}</b><table><tr><th></th><th>Pred No</th><th>Pred Yes</th></tr><tr><th>Actual No</th><td>${m.tn}</td><td>${m.fp}</td></tr><tr><th>Actual Yes</th><td>${m.fn}</td><td>${m.tp}</td></tr></table>`).join('');
$('#tt').innerHTML=`<p>Root split: <b>${T.attr||'—'}</b></p>`+tr(T);
const eq=(o,nm)=>`<p><code>${o.b.map((v,i)=>i?` ${v<0?'−':'+'} ${fx(Math.abs(v),2)}·${nm[i-1]}`:fx(v,2)).join('')}</code></p><p>R² = <b>${o.r2.toFixed(3)}</b> · MAE = <b>${fx(o.mae,2)}</b></p>`;
const g1=reg(F.map(r=>M1X.map(c=>r[c])),F.map(r=>r[M1T])),g2=reg(F.map(r=>M2X.map(c=>r[c])),F.map(r=>r[M2T]));R.g=[g1,g2];
$('#r1').innerHTML=eq(g1,M1X);$('#r2').innerHTML=eq(g2,M2X);
mk('c7',{type:'scatter',data:{datasets:[{label:'Actual',data:F.map(r=>({x:r[M1X[0]],y:r[M1T]})),backgroundColor:'rgba(47,91,234,.35)',pointRadius:3},{label:'Predicted (Model 1)',data:F.map((r,i)=>({x:r[M1X[0]],y:g1.pr[i]})),backgroundColor:'rgba(229,72,77,.6)',pointRadius:3}]},options:{plugins:{title:{display:true,text:M1T+' vs '+M1X[0]}},scales:{x:{title:{display:true,text:M1X[0]}},y:{title:{display:true,text:M1T}}}}});
const cl=km(F),NM=KS().map(j=>'Cluster '+j+(j==0?' · lowest '+KF[0]:j==KK()-1?' · highest '+KF[0]:' · mid'));R.k=KS().map(j=>{const m=F.filter((_,i)=>cl[i]==j);return{nm:NM[j],n:m.length,a:mean(m,r=>r[KF[0]]),b:mean(m,r=>r[KF[1]]),c:mean(m,r=>r[KF[2]]),at:100*m.filter(isY).length/(m.length||1)}});
const hi=Math.max(...R.k.map(k=>k.at));$('#kt').innerHTML=`<table><tr><th>Segment</th><th>Size</th><th>${KF[0]}</th><th>${KF[1]}</th><th>${KF[2]}</th><th>Attrition</th></tr>${R.k.map(k=>`<tr><td>${k.nm}</td><td>${k.n} (${fx(100*k.n/n,0)}%)</td><td>${fx(k.a)}</td><td>${fx(k.b)}</td><td>${fx(k.c)}</td><td class="${k.at==hi?'y':''}">${fx(k.at)}%</td></tr>`).join('')}</table>`;
mk('c8',{type:'scatter',data:{datasets:KS().map(j=>({label:NM[j],data:F.map((r,i)=>cl[i]==j?{x:r[KF[0]],y:r[KF[1]]}:null).filter(Boolean),backgroundColor:PAL[j],pointRadius:3}))},options:{plugins:{title:{display:true,text:'Segments: '+KF[0]+' vs '+KF[1]}},scales:{x:{title:{display:true,text:KF[0]}},y:{title:{display:true,text:KF[1]}}}}});
const best=M1.acc>=M2.acc?['Decision tree',M1]:['Naive Bayes',M2],hk=R.k.reduce((a,b)=>b.at>a.at?b:a),tr1=R.rules[0];
$('#in').innerHTML=`<ul><li>Overall attrition: <b>${fx(100*ya/n)}%</b> of ${n} employees.</li><li>Top predictors (Information Gain): <b>${ig.slice(0,4).map(x=>x[0]).join(', ')}</b>.</li><li>Best classifier on hold-out: <b>${best[0]}</b> (${(best[1].acc*100).toFixed(1)}% accuracy).</li>${tr1?`<li>Strongest association rule: <b>${tr1.name}</b> ⇒ ${TGT}=${POS} (confidence ${tr1.c.toFixed(2)}, lift ${tr1.l.toFixed(2)}).</li>`:''}<li>Income model: R² = ${g1.r2.toFixed(3)}; tenure model: R² = ${g2.r2.toFixed(3)}.</li><li>Highest-risk segment: <b>${hk.nm}</b> — ${fx(hk.at)}% attrition, ${KF[0]} ${fx(hk.a)}, ${KF[1]} ${fx(hk.b)}.</li></ul><h3>Recommendations</h3><ul><li>Monitor and intervene on the top drivers: ${ig.slice(0,3).map(x=>x[0]).join(', ')}.</li><li>Run early-intervention programmes for the highest-risk segment (${hk.nm}).</li><li>Use the What-if tab to score individual records before acting.</li></ul>`;if(window.afterRender)afterRender()}
function load(rows){const t=[...document.querySelectorAll('.pn')].findIndex(p=>p.classList.contains('on'));if(rows!==RAW)TGOVR='';RAW=rows;ALL=analyze(RAW);shell();render();if(t>0)go(t)}
$('#nv').innerHTML=TABS.map((t,i)=>`<button onclick="go(${i})">${t}</button>`).join('');
$('#dm').onclick=()=>{DSNAME='Demo (generated)';load(demo())};
const cs=getComputedStyle(document.documentElement);Chart.defaults.color=cs.getPropertyValue('--tx');Chart.defaults.borderColor=cs.getPropertyValue('--bd');

libInit();const sb=SLOT.B;if(LIB[sb]&&(!HIST[sb]||!HIST[sb].top)){DSNAME=sb;load(parse(LIB[sb].text))}
DSNAME=SLOT.A;load(parse(LIB[SLOT.A].text));
