/* Dataset overview, current-vs-previous dataset comparison, extra per-model graphs, colourful palette */
const HRN='HR_Employee_Attrition_2500.csv',CHN='Customer_Churn_dataset2.csv',PALX=['#6366f1','#ec4899','#14b8a6','#f59e0b','#3b82f6','#ef4444','#8b5cf6','#10b981','#f97316','#06b6d4'];
let HIST={},DSNAME='Dataset',CMPSEL='';try{HIST=JSON.parse(localStorage.getItem('dwm_hist')||'{}')}catch(e){}
function colorize(cfg){if(cfg.type!='bar'||!cfg.data)return;const d=cfg.data.datasets;if(d.length==1&&typeof d[0].backgroundColor=='string')d[0].backgroundColor=cfg.data.labels.map((_,i)=>PALX[i%PALX.length])}
function extraShell3(){const cv=(ids,h=300)=>ids.map(i=>`<div class="c"><div class="ch" style="height:${h}px"><canvas id="${i}"></canvas></div></div>`).join('');
$('#p0').insertAdjacentHTML('afterend',`<section class="pn" id="p10"><div class="g k" id="ovk"></div><div class="g">${cv(['c31','c32','c33','c34'])}<div class="c w"><h3>Column-by-column summary (raw data)</h3><div id="ovt"></div></div></div></section><section class="pn" id="p11"><div class="c" style="margin-bottom:14px"><div class="sc"><h3 style="margin:0">Compare current dataset with</h3><select id="cps" onchange="CMPSEL=this.value;cmpData()"></select><button onclick="slotBoth()">Analyse slots A &amp; B</button></div><div id="cpm" class="mu"></div></div><div class="g">${cv(['c20','c21','c22','c23'],320)}<div class="c w"><h3>Side-by-side metrics</h3><div id="cpt"></div></div></div></section>`);
$('#p4 .g').insertAdjacentHTML('beforeend',cv(['c24','c26','c27','c28'],280));$('#p5 .g').insertAdjacentHTML('beforeend',cv(['c29'],280));$('#p6 .g').insertAdjacentHTML('beforeend',cv(['c30'],280));
$('#p7').insertAdjacentHTML('beforeend',`<div class="c" style="margin-top:14px"><div class="ch" style="height:340px"><canvas id="c25"></canvas></div></div>`);if(window.extraShell4)extraShell4()}
function extraRender3(){ovw();snap();cmpData();cmpMore();if(window.extraRender4)extraRender4()}
function ovw(){const P=PREP,cs=Object.keys(SCH).filter(k=>k[0]!='_'),tc={},miss=sum(cs,c=>SCH[c].miss);cs.forEach(c=>tc[SCH[c].t]=(tc[SCH[c].t]||0)+1);
$('#ovk').innerHTML=[['Rows (raw)',P.n0.toLocaleString()],['Columns',P.cols0],['Total cells',P.cells0.toLocaleString()],['Missing cells',miss.toLocaleString()+' ('+fx(100*miss/P.cells0,2)+'%)'],['Columns with missing',cs.filter(c=>SCH[c].miss).length],['Duplicate rows',P.dups],['Numeric / categorical predictors',NUM.length+' / '+(COLS.length-NUM.length)],['Rows after cleaning',P.n1.toLocaleString()]].map(([l,v])=>`<div class="c"><div class="kl">${l}</div><div class="kv" style="font-size:20px">${v}</div></div>`).join('');
mk('c31',{type:'bar',data:{labels:cs,datasets:[{label:'Missing %',data:cs.map(c=>+(100*SCH[c].miss/P.n0).toFixed(2)),backgroundColor:'#ec4899'}]},options:{plugins:{legend:{display:false},title:{display:true,text:'Missing values per column (% of rows)'}},scales:{y:{beginAtZero:true}}}});
mk('c32',{type:'doughnut',data:{labels:Object.keys(tc),datasets:[{data:Object.values(tc),backgroundColor:PALX}]},options:{plugins:{title:{display:true,text:'Detected column types'}}}});
mk('c33',{type:'bar',data:{labels:['Raw rows','After missing-value step','Final rows (after duplicates)'],datasets:[{label:'Rows',data:[P.n0,P.n0-P.rowsOther,P.n1],backgroundColor:'#6366f1'}]},options:{plugins:{legend:{display:false},title:{display:true,text:'Rows through the cleaning pipeline'}},scales:{y:{beginAtZero:true}}}});
const b=[0,0,0,0];RAW.forEach(r=>b[Math.min(3,cs.filter(c=>r[c]==null).length)]++);
mk('c34',{type:'bar',data:{labels:['0 missing','1 missing','2 missing','3+ missing'],datasets:[{label:'Rows',data:b,backgroundColor:'#14b8a6'}]},options:{plugins:{legend:{display:false},title:{display:true,text:'Rows by number of missing cells'}},scales:{y:{beginAtZero:true}}}});
const st=c=>{const v=RAW.map(r=>r[c]).filter(x=>x!=null);if(!v.length)return'–';if(SCH[c].num)return`${fx(Math.min(...v),2)} / ${fx(sum(v)/v.length,2)} / ${fx(Math.max(...v),2)}`;const g={};v.forEach(x=>g[x]=(g[x]||0)+1);const t=Object.keys(g).sort((x,y)=>g[y]-g[x])[0];return`${t} (${fx(100*g[t]/v.length,1)}%)`};
$('#ovt').innerHTML=`<table><tr><th>Column</th><th>Type</th><th>Distinct</th><th>Missing</th><th>Min / Mean / Max  or  Top value</th></tr>${cs.map(c=>`<tr><td>${c}</td><td>${SCH[c].t}</td><td>${SCH[c].dist}</td><td class="${SCH[c].miss?'y':''}">${SCH[c].miss} (${fx(100*SCH[c].miss/P.n0,1)}%)</td><td>${st(c)}</td></tr>`).join('')}</table>`}
function snap(){const P=PREP,cs=Object.keys(SCH).filter(k=>k[0]!='_'),[t,nb]=R.cm,[g1,g2]=R.g;
HIST[DSNAME]={name:DSNAME,t:Date.now(),rows:P.n0,cols:P.cols0,preds:COLS.length,miss:100*sum(cs,c=>SCH[c].miss)/P.cells0,dup:100*P.dups/P.n0,out:100*P.outCells/P.cells0,rate:100*ALL.filter(isY).length/ALL.length,target:TGT,acc1:100*t.m.acc,acc2:100*nb.m.acc,auc1:100*t.auc,auc2:100*nb.auc,r2a:100*g1.r2,r2b:100*g2.r2,risk:Math.max(...R.k.map(k=>k.at)),top:TOPA(5).join(', '),imputed:P.imputed,dupN:P.dups,outN:P.outCells,kf:KF.join(', '),m1:M1T+' ~ '+M1X.join(' + ')};
try{localStorage.setItem('dwm_hist',JSON.stringify(HIST))}catch(e){}}
function cmpData(){const cur=HIST[DSNAME],ot=Object.values(HIST).filter(s=>s.name!=DSNAME).sort((a,b)=>b.t-a.t);if(!cur)return;
if(!HIST[CMPSEL]||CMPSEL==DSNAME){const pn=SLOT.A==DSNAME?SLOT.B:SLOT.A;CMPSEL=HIST[pn]&&pn!=DSNAME?pn:(ot[0]?ot[0].name:'')}$('#cps').innerHTML=ot.map(s=>`<option ${s.name==CMPSEL?'selected':''}>${s.name}</option>`).join('');const pv=HIST[CMPSEL];
if(!pv){$('#cpm').textContent='No other dataset recorded yet - click "Load 2nd dataset" or upload another CSV, then return here.';return}
$('#cpm').textContent=`Current: ${cur.name} (target ${cur.target})  vs  Previous: ${pv.name} (target ${pv.target}). Values are recorded with the filters/settings active when each dataset was last analysed.`;
const two=(id,title,keys,labels,y={})=>mk(id,{type:'bar',data:{labels,datasets:[{label:'Current: '+cur.name,data:keys.map(k=>+cur[k].toFixed(2)),backgroundColor:'#6366f1'},{label:'Previous: '+pv.name,data:keys.map(k=>+pv[k].toFixed(2)),backgroundColor:'#ec4899'}]},options:{plugins:{title:{display:true,text:title}},scales:{y:Object.assign({beginAtZero:true},y)}}});
two('c20','Data quality & class balance (%)',['miss','dup','out','rate'],['Missing cells','Duplicate rows','Outlier cells','Target rate']);
two('c21','Dataset size (log scale)',['rows','cols','preds'],['Rows','Columns','Predictors'],{type:'logarithmic',beginAtZero:false});
two('c22','Model performance (%)',['acc1','acc2','auc1','auc2','r2a','r2b'],['Tree acc.','NB acc.','Tree AUC','NB AUC','Regr. R² M1','Regr. R² M2']);
const rd=s=>[100-s.miss,s.acc1,s.acc2,s.auc1,Math.max(0,s.r2a),100-2*Math.abs(s.rate-50)];
mk('c23',{type:'radar',data:{labels:['Completeness','Tree acc.','NB acc.','Tree AUC','Regr. R²','Class balance'],datasets:[{label:cur.name,data:rd(cur).map(v=>+v.toFixed(1)),borderColor:'#6366f1',backgroundColor:'#6366f133'},{label:pv.name,data:rd(pv).map(v=>+v.toFixed(1)),borderColor:'#ec4899',backgroundColor:'#ec489933'}]},options:{plugins:{title:{display:true,text:'Overall comparison radar'}},scales:{r:{min:0,max:100}}}});
const L=[['Rows','rows'],['Columns','cols'],['Predictors','preds'],['Target column','target'],['Missing cells %','miss'],['Duplicate rows %','dup'],['Outlier cells %','out'],['Target rate %','rate'],['Tree accuracy %','acc1'],['Naive Bayes accuracy %','acc2'],['Tree AUC %','auc1'],['Naive Bayes AUC %','auc2'],['Regression R² Model 1 %','r2a'],['Regression R² Model 2 %','r2b'],['Highest cluster risk %','risk']];
$('#cpt').innerHTML=`<table><tr><th>Metric</th><th>${cur.name}</th><th>${pv.name}</th><th>Difference</th></tr>${L.map(([l,k])=>{const a=cur[k],b=pv[k],n=typeof a=='number',d=a-b;return`<tr><td>${l}</td><td><b>${n?fx(a,2):a}</b></td><td>${n?fx(b,2):b}</td><td class="${n&&d>0?'n':n&&d<0?'y':''}">${n?(d>0?'+':'')+fx(d,2):''}</td></tr>`}).join('')}</table>`}
function cmpMore(){const res=R.cm,CL=['#6366f1','#ec4899','#14b8a6'],te=R.sp.te;
mk('c24',{type:'radar',data:{labels:['Accuracy','Precision','Recall','F1','AUC'],datasets:res.map((r,i)=>({label:r.nm,data:[r.m.acc,r.m.pr,r.m.rc,r.m.f1,r.auc].map(v=>+(v*100).toFixed(1)),borderColor:CL[i],backgroundColor:CL[i]+'22'}))},options:{plugins:{title:{display:true,text:'Comparative analytics - classifier radar'}},scales:{r:{min:0,max:100}}}});
res.forEach((r,i)=>{const b=Array.from({length:10},()=>[0,0]);r.sc.forEach((s,j)=>b[Math.min(9,Math.floor(s*10))][isY(te[j])?0:1]++);
mk('c'+(26+i),{type:'bar',data:{labels:b.map((_,k)=>k*10+'-'+(k*10+10)+'%'),datasets:[{label:String(POS),data:b.map(x=>x[0]),backgroundColor:'#ef4444'},{label:'other',data:b.map(x=>x[1]),backgroundColor:'#3b82f6'}]},options:{plugins:{title:{display:true,text:r.nm+' - predicted-risk distribution'}},scales:{x:{stacked:true},y:{stacked:true}}}})});
const g2=R.g[1];mk('c29',{type:'scatter',data:{datasets:[{label:'Actual',data:F.map(r=>({x:r[M2X[0]],y:r[M2T]})),backgroundColor:'#6366f166',pointRadius:3},{label:'Predicted (Model 2)',data:F.map((r,i)=>({x:r[M2X[0]],y:g2.pr[i]})),backgroundColor:'#f59e0b99',pointRadius:3}]},options:{plugins:{title:{display:true,text:'Model 2: '+M2T+' vs '+M2X[0]}},scales:{x:{title:{display:true,text:M2X[0]}},y:{title:{display:true,text:M2T}}}}});
const mn=KF.map(c=>Math.min(...F.map(r=>r[c]))),mx=KF.map(c=>Math.max(...F.map(r=>r[c])));
mk('c30',{type:'bar',data:{labels:KF,datasets:R.k.map((k,i)=>({label:'Cluster '+i,data:[k.a,k.b,k.c].map((v,d)=>+(100*(v-mn[d])/(mx[d]-mn[d]||1)).toFixed(1)),backgroundColor:PALX[i%10]}))},options:{plugins:{title:{display:true,text:'Cluster profiles (mean as % of feature range)'}},scales:{y:{beginAtZero:true,max:100}}}});
const n=Dm.length,base=100*Dm.filter(isY).length/n,rk=TOPA(8).map(c=>{const g={};Dm.forEach(r=>(g[r[c]]=g[r[c]]||[0,0])[isY(r)?0:1]++);let b=null;for(const v in g){const t=g[v][0]+g[v][1];if(t>=.05*n){const p=100*g[v][0]/t;if(!b||p>b[1])b=[v,p]}}return b?[c+' = '+b[0],+b[1].toFixed(1)]:null}).filter(Boolean);
mk('c25',{type:'bar',data:{labels:rk.map(x=>x[0]),datasets:[{label:'Highest-risk value: '+TGT+' rate %',data:rk.map(x=>x[1]),backgroundColor:'#f97316'},{type:'line',label:'Overall rate %',data:rk.map(()=>+base.toFixed(1)),borderColor:'#6366f1',pointRadius:0,borderWidth:2}]},options:{plugins:{title:{display:true,text:'Comparative analytics - highest-risk value of each top attribute vs overall'}},scales:{y:{beginAtZero:true}}}})}
