/* Preprocessing % report, attribute-detection panel, model-comparison graphs */
function nbp(tr){const m={Yes:{n:0,c:{}},No:{n:0,c:{}}};tr.forEach(r=>{const z=m[isY(r)?'Yes':'No'];z.n++;COLS.forEach(c=>{const k=c+'='+r[c];z.c[k]=(z.c[k]||0)+1})});
return r=>{const s={};for(const k in m){s[k]=Math.log((m[k].n+1)/tr.length);COLS.forEach(c=>s[k]+=Math.log(((m[k].c[c+'='+r[c]]||0)+1)/(m[k].n+4)))}return 1/(1+Math.exp(s.No-s.Yes))}}
function roc(sc,te){const o=sc.map((s,i)=>[s,isY(te[i])?1:0]).sort((a,b)=>b[0]-a[0]),P=sum(o,x=>x[1]),N=o.length-P;let tp=0,fp=0,auc=0,px=0,py=0;const pts=[{x:0,y:0}];
o.forEach(([s,y])=>{y?tp++:fp++;const x=fp/(N||1),yy=tp/(P||1);auc+=(x-px)*(yy+py)/2;px=x;py=yy;pts.push({x,y:yy})});return{pts,auc}}
function extraShell2(){const cv=(ids,h)=>ids.map(i=>`<div class="c"><div class="ch" style="height:${h}px"><canvas id="${i}"></canvas></div></div>`).join('');
$('#p2 .g').insertAdjacentHTML('afterbegin',`<div class="c w"><h3>Auto attribute detection</h3><div class="sc"><span id="adm"></span>Target column <select id="tg" onchange="TGOVR=this.value;load(RAW)"></select></div><div id="ad"></div></div><div class="c"><h3>Preprocessing options (live)</h3><div id="ppo"></div></div><div class="c"><h3>Percentage of data changed</h3><div id="ppt"></div><div class="ch" style="height:260px"><canvas id="c9"></canvas></div></div>`);
$('#ppo').innerHTML=[['dup','Remove duplicate records (ignoring ID columns)'],['imp','Impute missing values (median / mode); off = drop those rows'],['cap','Cap outliers with the IQR rule; off = only flag them']].map(([k,l])=>`<label class="fl"><input type="checkbox" ${PP[k]?'checked':''} onchange="PP.${k}=this.checked;load(RAW)"> ${l}</label>`).join('');
$('#p4 .g').insertAdjacentHTML('beforeend',`<div class="c w"><h3>Model comparison — live (changes with filters, tree depth and split)</h3></div>`+cv(['c10','c11'],300)+`<div class="c w"><div class="ch" style="height:300px"><canvas id="c12"></canvas></div></div>`+cv(['c13','c14','c15'],220));
$('#p5 .g').insertAdjacentHTML('beforeend',cv(['c16','c17'],280));$('#p6 .g').insertAdjacentHTML('beforeend',cv(['c18','c19'],280));if(window.extraShell3)extraShell3()}
function extraRender(){const P=PREP;if($('#star'))$('#star').innerHTML=starHTML();const cs=Object.keys(SCH).filter(k=>k[0]!='_');
$('#adm').innerHTML=`Detected <b>${P.n0}</b> rows × <b>${P.cols0}</b> columns · target <b>${TGT}</b> (positive = <b>${POS}</b>) · ${CONT.length} continuous + ${COLS.length-CONT.length} categorical/ordinal predictors &nbsp;`;
$('#tg').innerHTML=cs.filter(c=>['categorical','ordinal','continuous'].includes(SCH[c].t)&&SCH[c].dist<=10).map(c=>`<option ${c==TGT?'selected':''}>${c}</option>`).join('');
$('#ad').innerHTML=`<table><tr><th>Column</th><th>Detected type</th><th>Role</th><th>Distinct</th><th>Missing</th><th>Info gain</th></tr>${cs.map(c=>`<tr><td>${c}</td><td>${SCH[c].t}</td><td class="${c==TGT?'y':''}">${SCH[c].role}</td><td>${SCH[c].dist}</td><td>${fx(100*SCH[c].miss/P.n0,1)}%</td><td>${SCH._ig[c]!=null?SCH._ig[c].toFixed(4):'–'}</td></tr>`).join('')}</table>`;
const pc=(x,b)=>100*x/b,rw=[['Identifier columns removed',`${P.ids} of ${P.cols0} columns`,pc(P.ids,P.cols0),'columns'],['Duplicate records removed',`${P.dups} of ${P.n0}`,pc(P.dups,P.n0),'records'],['Other records removed (missing / no target)',`${P.rowsOther}`,pc(P.rowsOther,P.n0),'records'],['Missing cells imputed',`${P.imputed} cells`,pc(P.imputed,P.cells0),'cells'],[PP.cap?'Outlier cells capped (IQR)':'Outlier cells flagged (IQR, unchanged)',`${P.outCells} cells`,pc(P.outCells,P.cells0),'cells'],['Continuous values discretized (3 bins)',`${P.n1*P.contN} cells`,pc(P.n1*P.contN,P.cells0),'cells'],['Categorical values encoded',`${P.n1*P.catN} cells`,pc(P.n1*P.catN,P.cells0),'cells'],['Features standardized (K-Means)',`${P.n1*3} cells`,pc(P.n1*3,P.cells0),'cells']],alt=P.imputed+(PP.cap?P.outCells:0);
$('#ppt').innerHTML=`<table><tr><th>Step</th><th>Amount</th><th>% of data</th><th>Basis</th></tr>${rw.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td><b>${fx(r[2],2)}%</b></td><td class="mu">${r[3]}</td></tr>`).join('')}</table><p>Raw values altered (imputed${PP.cap?' + capped':''}): <b>${fx(pc(alt,P.cells0),2)}%</b> of ${P.cells0.toLocaleString()} cells · records kept: <b>${P.n1}</b> of ${P.n0} (<b>${fx(pc(P.n1,P.n0),1)}%</b>)</p>`;
mk('c9',{type:'bar',data:{labels:rw.map(r=>r[0].split(' (')[0]),datasets:[{data:rw.map(r=>+r[2].toFixed(2)),backgroundColor:'#2f5bea'}]},options:{indexAxis:'y',plugins:{legend:{display:false},title:{display:true,text:'% of data affected per step'}}}});
cmpClassif();cmpReg();cmpClust();if(window.extraRender3)extraRender3()}
function cmpClassif(){const{trn,te,T}=R.sp,ptp=(t,r)=>{while(t.attr&&t.ch[r[t.attr]])t=t.ch[r[t.attr]];return(t.y+.5)/(t.n+1)},S1=tree(trn,COLS,1),CL=['#2f5bea','#e5484d','#1f9d6b'],
Ms=[['Decision Tree (depth '+TD()+')',r=>ptp(T,r)],['Naive Bayes',nbp(trn)],['Decision Stump',r=>ptp(S1,r)]],
res=Ms.map(([nm,f])=>{const sc=te.map(f);return{nm,sc,m:ev(te,r=>f(r)>=.5?'Yes':'No'),...roc(sc,te)}});R.cm=res;
mk('c10',{type:'bar',data:{labels:['Accuracy','Precision','Recall','F1','AUC'],datasets:res.map((r,i)=>({label:r.nm,backgroundColor:CL[i],data:[r.m.acc,r.m.pr,r.m.rc,r.m.f1,r.auc].map(v=>+(v*100).toFixed(1))}))},options:{plugins:{title:{display:true,text:'Model metrics (%) — hold-out set'}},scales:{y:{beginAtZero:true,max:100}}}});
mk('c11',{type:'scatter',data:{datasets:[...res.map((r,i)=>({label:r.nm+' (AUC '+r.auc.toFixed(2)+')',data:r.pts,showLine:true,pointRadius:0,borderColor:CL[i],borderWidth:2})),{label:'Chance',data:[{x:0,y:0},{x:1,y:1}],showLine:true,pointRadius:0,borderColor:'#999',borderDash:[5,5]}]},options:{plugins:{title:{display:true,text:'ROC curves'}},scales:{x:{title:{display:true,text:'False positive rate'},min:0,max:1},y:{title:{display:true,text:'True positive rate'},min:0,max:1}}}});
const ds=[1,2,3,4,5,6],tt=ds.map(d=>tree(trn,COLS,d)),ac=(t,s)=>+(100*s.filter(r=>(pt(t,r)=='Yes')==isY(r)).length/s.length).toFixed(1);
mk('c12',{type:'line',data:{labels:ds,datasets:[{label:'Train accuracy %',data:tt.map(t=>ac(t,trn)),borderColor:'#1f9d6b',tension:.3},{label:'Test accuracy %',data:tt.map(t=>ac(t,te)),borderColor:'#e5484d',tension:.3}]},options:{plugins:{title:{display:true,text:'Decision tree: accuracy vs depth (current depth = '+TD()+')'}},scales:{x:{title:{display:true,text:'Tree depth'}}}}});
res.forEach((r,i)=>mk('c'+(13+i),{type:'bar',data:{labels:['TN','FP','FN','TP'],datasets:[{data:[r.m.tn,r.m.fp,r.m.fn,r.m.tp],backgroundColor:['#1f9d6b','#f5a623','#f5a623','#2f5bea']}]},options:{plugins:{legend:{display:false},title:{display:true,text:r.nm+' — confusion counts'}}}}))}
function cmpReg(){const[g1,g2]=R.g,mu=c=>Math.abs(mean(F,r=>r[c]))||1,sd=c=>{const m=mean(F,r=>r[c]);return Math.sqrt(mean(F,r=>(r[c]-m)**2))||1};
mk('c16',{type:'bar',data:{labels:['M1: '+M1T,'M2: '+M2T],datasets:[{label:'R²',data:[g1.r2,g2.r2].map(v=>+v.toFixed(3)),backgroundColor:'#2f5bea'},{label:'MAE ÷ mean(target)',data:[g1.mae/mu(M1T),g2.mae/mu(M2T)].map(v=>+v.toFixed(3)),backgroundColor:'#e5484d'}]},options:{plugins:{title:{display:true,text:'Regression model comparison'}},scales:{y:{beginAtZero:true}}}});
mk('c17',{type:'bar',data:{labels:M1X,datasets:[{data:g1.b.slice(1).map((b,i)=>+(b*sd(M1X[i])/sd(M1T)).toFixed(3)),backgroundColor:'#1f9d6b'}]},options:{indexAxis:'y',plugins:{legend:{display:false},title:{display:true,text:'Model 1 predictor strength (standardized coefficients)'}}}})}
function cmpClust(){const ks=[2,3,4,5,6],w=ks.map(k=>{km(F,k);return Math.round(km.W)});
mk('c18',{type:'line',data:{labels:ks,datasets:[{data:w,borderColor:'#2f5bea',tension:.3}]},options:{plugins:{legend:{display:false},title:{display:true,text:'Elbow: within-cluster SS vs K (current K = '+KK()+')'}},scales:{x:{title:{display:true,text:'K'}}}}});
mk('c19',{type:'bar',data:{labels:R.k.map((k,i)=>'Cluster '+i),datasets:[{label:'% of records',data:R.k.map(k=>+(100*k.n/F.length).toFixed(1)),backgroundColor:'#2f5bea'},{label:TGT+' rate %',data:R.k.map(k=>+k.at.toFixed(1)),backgroundColor:'#e5484d'}]},options:{plugins:{title:{display:true,text:'Cluster size vs '+TGT+' rate'}},scales:{y:{beginAtZero:true}}}})}
